# Generated by Django 5.2.6 on 2025-10-01 08:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the category (e.g., 'Work', 'Personal', 'Health')", max_length=100)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code for UI theming', max_length=7)),
                ('description', models.TextField(blank=True, help_text='Optional description of the category')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, help_text='When this category was created')),
                ('user', models.ForeignKey(help_text='The user who created this category', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['user', 'name'], name='tracker_cat_user_id_ac5ed5_idx')],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('win', 'Daily Win'), ('gratitude', 'Gratitude Entry')], help_text='Type of entry: win or gratitude', max_length=10)),
                ('title', models.CharField(help_text='Brief title or summary of the entry', max_length=200)),
                ('content', models.TextField(help_text='Main content of the entry')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, help_text='When this entry was created')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='When this entry was last modified')),
                ('is_private', models.BooleanField(default=True, help_text='Privacy setting - currently all entries are private')),
                ('user', models.ForeignKey(help_text='The user who created this entry', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
                'ordering': ['-date_created'],
                'indexes': [models.Index(fields=['user', '-date_created'], name='tracker_ent_user_id_ce58e4_idx'), models.Index(fields=['entry_type'], name='tracker_ent_entry_t_048b93_idx')],
            },
        ),
    ]
