# Generated by Django 5.2.6 on 2025-10-01 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_category_unique_together_alter_category_color_and_more'),
    ]

    operations = [
    ]
