# Generated by Django 5.2.6 on 2025-10-01 10:07

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_add_model_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entry',
            name='mood_rating_range',
        ),
        migrations.RemoveIndex(
            model_name='entry',
            name='tracker_ent_entry_t_048b93_idx',
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_type',
            field=models.CharField(choices=[('win', 'Daily Win'), ('gratitude', 'Gratitude Entry')], db_index=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(django.db.models.functions.text.Lower('name'), name='idx_category_lower_name'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(condition=models.Q(('mood_rating__isnull', True), models.Q(('mood_rating__gte', 1), ('mood_rating__lte', 10)), _connector='OR'), name='mood_rating_null_or_between_1_10', violation_error_message='Mood rating must be between 1 and 10 (or left blank).'),
        ),
    ]
