# Generated by Django 5.2.6 on 2025-10-01 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_remove_entry_mood_rating_range_and_more'),
    ]

    operations = [
    ]
