# Generated by Django 5.2.6 on 2025-10-01 15:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20251001_1627'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-entry_date', '-date_created'], 'verbose_name_plural': 'Entries'},
        ),
        migrations.RemoveConstraint(
            model_name='entry',
            name='mood_rating_null_or_between_1_10',
        ),
        migrations.RemoveIndex(
            model_name='entry',
            name='tracker_ent_user_id_ce58e4_idx',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='entry_type',
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_date',
            field=models.DateField(blank=True, help_text='The date this entry is for', null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='gratitude_text',
            field=models.TextField(blank=True, help_text='Today I was grateful for...'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=models.TextField(blank=True, help_text='Details about your daily wins'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='mood_rating',
            field=models.IntegerField(blank=True, choices=[(1, '😰 Terrible'), (2, '😞 Bad'), (3, '😐 Meh'), (4, '🙂 Okay'), (5, '😊 Good'), (6, '😄 Great'), (7, '🤩 Amazing'), (8, '🥳 Fantastic'), (9, '✨ Incredible'), (10, '🌟 Perfect')], help_text='How was your mood today?', null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(blank=True, help_text='Short title for your daily win', max_length=200),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['user', '-entry_date'], name='tracker_ent_user_id_fa50f5_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['user', 'entry_date'], name='tracker_ent_user_id_e317b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(fields=('user', 'entry_date'), name='unique_entry_per_user_per_day', violation_error_message='You can only have one entry per day.'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(condition=models.Q(('mood_rating__isnull', True), ('mood_rating__in', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]), _connector='OR'), name='mood_rating_valid_choice', violation_error_message='Mood rating must be between 1 and 10.'),
        ),
    ]
